# Generated by Django 5.2.7 on 2026-05-15 03:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('organizer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organizer_name', models.CharField(max_length=100)),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'organizer',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'venue',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(decimal_places=2, max_digits=12)])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.customer')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_datetime', models.DateTimeField()),
                ('event_title', models.CharField(max_length=200)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.organizer')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.venue')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promotion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('promo_code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('NOMINAL', 'NOMINAL'), ('PERCENTAGE', 'PERCENTAGE')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.DecimalValidator(decimal_places=2, max_digits=12)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('usage_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'promotion',
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='ck_promotion_end_gte_start')],
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('quota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(decimal_places=2, max_digits=12)])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_categories', to='main.event')),
            ],
            options={
                'db_table': 'ticket_category',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_code', models.CharField(max_length=100, unique=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='main.order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='main.ticketcategory')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.AddField(
            model_name='organizer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to='main.useraccount'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='main.useraccount'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=50)),
                ('seat_number', models.CharField(max_length=10)),
                ('row_number', models.CharField(max_length=10)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='main.venue')),
            ],
            options={
                'db_table': 'seat',
            },
        ),
        migrations.CreateModel(
            name='EventArtist',
            fields=[
                ('event_artist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_artists', to='main.artist')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_artists', to='main.event')),
            ],
            options={
                'db_table': 'event_artist',
                'constraints': [models.UniqueConstraint(fields=('event', 'artist'), name='uq_event_artist_event_artist')],
            },
        ),
        migrations.CreateModel(
            name='OrderPromotion',
            fields=[
                ('order_promotion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_promotions', to='main.order')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_promotions', to='main.promotion')),
            ],
            options={
                'db_table': 'order_promotion',
                'constraints': [models.UniqueConstraint(fields=('promotion', 'order'), name='uq_order_promotion_promotion_order')],
            },
        ),
        migrations.CreateModel(
            name='HasRelationship',
            fields=[
                ('has_relationship_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_relationships', to='main.seat')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_relationships', to='main.ticket')),
            ],
            options={
                'db_table': 'has_relationship',
                'constraints': [models.UniqueConstraint(fields=('seat', 'ticket'), name='uq_has_relationship_seat_ticket'), models.UniqueConstraint(fields=('seat',), name='uq_has_relationship_seat_once')],
            },
        ),
        migrations.CreateModel(
            name='AccountRole',
            fields=[
                ('account_role_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_roles', to='main.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_roles', to='main.useraccount')),
            ],
            options={
                'db_table': 'account_role',
                'constraints': [models.UniqueConstraint(fields=('role', 'user'), name='uq_account_role_role_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('venue', 'section', 'row_number', 'seat_number'), name='uq_seat_venue_section_row_seatnum'),
        ),
    ]
